CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL,
  user_password TEXT NOT NULL
);

CREATE TABLE business (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  business_id TEXT NOT NULL
);

CREATE TABLE user_businesses (
  user_id INTEGER REFERENCES users(id) NOT NULL,
  business_id INTEGER REFERENCES business(id) NOT NULL,
  PRIMARY KEY (user_id, business_id)
);

